package opintoapuri;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2012.03.14 02:28:07 // Generated by ComTest
 *
 */
public class KurssitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa51 
   * @throws ApuriException when error
   */
  @Test
  public void testLisaa51() throws ApuriException {    // Kurssit: 51
    Kurssit kurssit = new Kurssit(); 
    Kurssi kurssi = new Kurssi(1); 
    Kurssi kurssi2 = new Kurssi(1); 
    Kurssi kurssi3 = new Kurssi(1); 
    Kurssi kurssi4 = new Kurssi(1); 
    kurssi3.annaOhj2(); 
    kurssit.lisaa(kurssi); 
    kurssit.lisaa(kurssi2); 
    kurssit.lisaa(kurssi3); 
    kurssit.lisaa(kurssi4); 
    assertEquals("From: Kurssit line: 63", kurssi, kurssit.anna(0)); 
    assertEquals("From: Kurssit line: 64", false, kurssit.anna(2) == kurssi4); 
    assertEquals("From: Kurssit line: 65", 4, kurssit.getLkm()); 
    try {
    assertEquals("From: Kurssit line: 66", kurssi, kurssit.anna(4));
    fail("Kurssit: 66 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}