package opintoapuri;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2012.03.14 02:27:59 // Generated by ComTest
 *
 */
public class KurssiTest {



  // Generated by ComTest BEGIN
  /** testGetTunnusNro88 */
  @Test
  public void testGetTunnusNro88() {    // Kurssi: 88
    Kurssi kurssi = new Kurssi(1); 
    Kurssi kurssi2 = new Kurssi(1); 
    assertEquals("From: Kurssi line: 91", 0, kurssi.getTunnusNro()); 
    kurssi.rekisteroiNro(); 
    kurssi2.rekisteroiNro(); 
    assertEquals("From: Kurssi line: 94", 1, kurssi.getTunnusNro()); 
    assertEquals("From: Kurssi line: 95", 2, kurssi2.getTunnusNro()); 
  } // Generated by ComTest END
}