package opintoapuri;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2012.03.16 21:54:59 // Generated by ComTest
 *
 */
public class OpintoapuriTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa33 
   * @throws ApuriException when error
   */
  @Test
  public void testLisaa33() throws ApuriException {    // Opintoapuri: 33
    Kurssit kurssit = new Kurssit(); 
    Kurssi kurssi = new Kurssi(1); 
    Kurssi kurssi2 = new Kurssi(1); 
    Kurssi kurssi3 = new Kurssi(1); 
    Kurssi kurssi4 = new Kurssi(1); 
    kurssi3.annaOhj2(); 
    kurssit.lisaa(kurssi); 
    kurssit.lisaa(kurssi2); 
    kurssit.lisaa(kurssi3); 
    kurssit.lisaa(kurssi4); 
    assertEquals("From: Opintoapuri line: 45", kurssi, kurssit.anna(0)); 
    assertEquals("From: Opintoapuri line: 46", false, kurssit.anna(2) == kurssi4); 
    assertEquals("From: Opintoapuri line: 47", 4, kurssit.getLkm()); 
    try {
    assertEquals("From: Opintoapuri line: 48", kurssi, kurssit.anna(4));
    fail("Opintoapuri: 48 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLaskePainotettuKA144 
   * @throws ApuriException when error
   */
  @Test
  public void testLaskePainotettuKA144() throws ApuriException {    // Opintoapuri: 144
    Opintoapuri opintoapuri = new Opintoapuri(); 
    Kurssi kurssi = new Kurssi(1); 
    Kurssi kurssi2 = new Kurssi(1); 
    Kurssi kurssi3 = new Kurssi(1); 
    Kurssi kurssi4 = new Kurssi(2); 
    Opintokokonaisuus kaupKand = new Opintokokonaisuus(); 
    Opintokokonaisuus jokuToinen = new Opintokokonaisuus(); 
    kaupKand.annaKaupKand(); 
    jokuToinen.annaKaupKand(); 
    kaupKand.rekisteroi(); 
    jokuToinen.rekisteroi(); 
    kurssi.annaOhj2(); 
    kurssi2.annaOhj2(); 
    kurssi3.annaOhj2(); 
    kurssi4.annaOhj2(); 
    opintoapuri.lisaa(kaupKand); 
    opintoapuri.lisaa(jokuToinen); 
    opintoapuri.lisaa(kurssi); 
    opintoapuri.lisaa(kurssi2); 
    opintoapuri.lisaa(kurssi3); 
    opintoapuri.lisaa(kurssi4); 
    kurssi.setArvolause(5); 
    kurssi.setLaajuus(4); 
    kurssi2.setArvolause(2); 
    kurssi2.setLaajuus(6); 
    kurssi3.setArvolause(0); 
    kurssi3.setLaajuus(10); 
    opintoapuri.laskeKeskiarvot(1); 
    assertEquals("From: Opintoapuri line: 175", 3.5, opintoapuri.getKeskiarvo(kaupKand.getTunnusNro()), 0.1); 
    assertEquals("From: Opintoapuri line: 176", 3.5, opintoapuri.getPainotettuKA(kaupKand.getTunnusNro()), 0.1); 
  } // Generated by ComTest END
}